### ISSUE TITLE
Please use %?RESOURCES<key> directly instead.

### ISSUE THREAD

**Issue by librasteve** [antononcube/Raku-Chemistry-Stoichiometry#2]
hey anton

saw this in an install today -i think its a pretty easy fix

===> Staging Chemistry::Stoichiometry:ver<0.1.6>:auth<zef:antononcube>:api<1>
Saw 1 occurrence of deprecated code.
================================================================================
Method Str (from Distribution::Resource) seen at:
  /home/xxx/.rakubrew/versions/moar-2024.03/share/perl6/site/sources/978310083AD9011C8F98B263FB7A6CF0339EAEEC (Chemistry::Stoichiometry::ResourceAccess), lines 54,87
Please use %?RESOURCES<key> directly instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!
Saw 1 occurrence of deprecated code.
================================================================================
Method Str (from Distribution::Resource) seen at:
  /home/xxx/.rakubrew/versions/moar-2024.03/share/perl6/site/sources/978310083AD9011C8F98B263FB7A6CF0339EAEEC (Chemistry::Stoichiometry::ResourceAccess), lines 54,87
Please use %?RESOURCES<key> directly instead.

**Comment by antononcube** [comment]
Thanks for filing this issue! Should be fixed with the version 0.1.8 of the package.

**Comment by antononcube** [comment]
Fixed with a [PR by @coke](https://github.com/antononcube/Raku-Chemistry-Stoichiometry/pull/3).
